# Generated by Django 3.0.3 on 2020-04-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repartidor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartidor',
            name='correo_repartidor',
        ),
    ]
