# Generated by Django 3.0.3 on 2020-04-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repartidor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repartidor',
            options={'verbose_name_plural': 'Repartidores'},
        ),
    ]
