# Generated by Django 3.0.3 on 2020-04-07 00:54

from django.db import migrations, models
import platillo.models


class Migration(migrations.Migration):

    dependencies = [
        ('platillo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='imagen',
            field=models.ImageField(null=True, upload_to=platillo.models.directorio_imagen),
        ),
    ]
