# Generated by Django 3.0.3 on 2020-04-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platillo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='platillo',
            table='platillo',
        ),
    ]
