# Generated by Django 3.0.3 on 2020-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platillo', '0002_platillo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
