# Generated by Django 3.0.3 on 2020-06-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200604_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad_carrito',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrito',
            name='precio_platillo_carrito',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id_cliente_carrito',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id_platillo_carrito',
            field=models.PositiveIntegerField(),
        ),
    ]
