# Generated by Django 3.0.3 on 2020-06-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200604_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad_carrito',
        ),
    ]
