# Generated by Django 3.0.3 on 2020-06-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_carrito_cantidad_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='nombre_platillo_carrito',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together={('nombre_platillo_carrito', 'id_cliente_carrito')},
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='id_platillo_carrito',
        ),
    ]
