# Generated by Django 3.0.3 on 2020-06-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_auto_20200606_1314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='direccion',
            unique_together={('id_cliente', 'descripcion_direccion')},
        ),
    ]
