# Generated by Django 3.0.3 on 2020-06-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_auto_20200606_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
