# Generated by Django 3.0.3 on 2020-06-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_auto_20200606_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Cliente'),
        ),
    ]
