# Generated by Django 3.0.3 on 2020-04-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=30)),
            ],
        ),
    ]
