# Generated by Django 3.0.3 on 2020-04-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200408_1202'),
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoorden',
            options={'verbose_name_plural': 'EstadosOrden'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterField(
            model_name='orden',
            name='direccion_entrega_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Direccion'),
        ),
    ]
