# Generated by Django 3.0.3 on 2020-04-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='direccion_entrega',
            new_name='direccion_entrega_orden',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='id_cliente',
            new_name='id_cliente_orden',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='id_estado',
            new_name='id_estado_orden',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='id_platillo',
            new_name='id_platillo_orden',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='id_repartidor',
            new_name='id_repartidor_orden',
        ),
    ]
